codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        if_not_found: failure
    
          

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
