name: Upload coverage

on:
  pull_request: {}
  push: { branches: [master] }


jobs:
  uploadCoverage:
    name: Upload Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        #fixes:
            #- "C:/Projects/GitHub/test_codecov_io/::"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: "Asteroids/CodeCoverage/Asteroids-opencov/Recording/RecordingCoverageResults_0000.xml"
